---
title: "Data Munging with data.table"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
---

<br>

**Note**: Assuming you have `Master.csv` in the same project folder.

<br>

# Importing CSV as Data Table (instead of normal Data Frame)

```{r}
library(data.table)
d_master = fread("Master.csv")
```


```{r}
str(d_master)
```

<br>

# Subsetting (Basics)


```{r}
# Subset rows using i (e.g. find all players with "David" in "nameGiven")
d_master[nameGiven %like% "David"] # using i only
```


```{r}
# Subset rows using i, calculate something using j
avg_birthYear = d_master[nameGiven %like% "David",       # i
                         mean(birthYear, na.rm = TRUE)]  # j
avg_birthYear
```



```{r}
# Subset rows using i, calculate something using j, group by using 'by'
avg_birthYear_country = d_master[nameGiven %like% "David",       # i
                                 mean(birthYear, na.rm = TRUE),  # j
                                 by = birthCountry]                # by
avg_birthYear_country
```













